/** @type {import('tailwindcss').Config} */
module.exports = {
  // All source dirs that may contain `className` strings.
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c6c6c7",
        "outline": "#8e9192",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#ffdad7",
        "tertiary": "#ffffff",
        "surface-bright": "#3a3939",
        "surface": "#131313",
        "surface-container-low": "#1c1b1b",
        "secondary-container": "#a90219",
        "on-secondary": "#68000b",
        "inverse-on-surface": "#313030",
        "on-surface": "#e5e2e1",
        "on-secondary-container": "#ffb3ad",
        "on-tertiary-container": "#5a6578",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#636565",
        "on-primary-fixed-variant": "#454747",
        "primary-fixed": "#e2e2e2",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#e2e2e2",
        "on-tertiary-fixed-variant": "#3c475a",
        "tertiary-fixed": "#d8e3fa",
        "on-secondary-fixed": "#410004",
        "on-surface-variant": "#c4c7c8",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#bcc7dd",
        "secondary": "#ffb3ae",
        "background": "#131313",
        "tertiary-container": "#d8e3fa",
        "secondary-fixed-dim": "#ffb3ae",
        "on-background": "#e5e2e1",
        "primary": "#ffffff",
        "on-tertiary-fixed": "#111c2c",
        "on-tertiary": "#263142",
        "surface-container": "#201f1f",
        "on-primary": "#2f3131",
        "error-container": "#93000a",
        "on-primary-fixed": "#1a1c1c",
        "surface-tint": "#c6c6c7",
        "outline-variant": "#444748",
        "error": "#ffb4ab",
        "surface-container-highest": "#353534",
        "surface-dim": "#131313",
        "surface-variant": "#353534",
        "inverse-primary": "#5d5f5f",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#930014"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "stack-sm": "8px",
        "stack-xl": "80px",
        "stack-lg": "48px",
        "margin-mobile": "20px",
        "stack-md": "24px",
        "margin-desktop": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "body-md": ["Inter"],
        "headline-xl": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "caption": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["60px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "caption": ["14px", { lineHeight: "1.4", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
};
